[theme]
# Theme name displayed in the UI for theme selection.
name = 'test-theme'

# Used to style primary interface elements. It's the color displayed most frequently across your app's screens and components. Examples of widgets using this color are st.slider and st.checkbox.
primaryColor = 'green'

# Used to style secondary interface elements. It provides more ways to accent and distinguish your app. Having it is optional.
secondaryColor = '#392FA0'

# Background color for the main container.
backgroundColor = '#273346'

# Used as the background for most widgets. Examples of widgets with this background are st.sidebar, st.text_input, st.date_input.
secondaryBackgroundColor = '#B9F1C0'

# Font color for the page.
textColor = '#FFFFFF'

# Font family (serif | sans-serif | mono) for the page. Will not impact code areas.
# Default: "sans serif"
font = "sans-serif"
